### ISSUE TITLE
Fix "slowness" in ios

### ISSUE THREAD

**Issue by nunoh** [Digitopia/Gamult#48] opened 2015-07-07 15:53 UTC
Whenever the particles hit the ground to play the sound there is a visible FPS drop.

**Comment by nunoh** [comment] 2015-07-20 00:49
It's related with the images.. When the `data` folder wasn't being included it was constantly at 60 FPS with all particles being drawn.

**Comment by nunoh** [comment] 2015-12-08 18:02
@Oscar-Rodrigues What's the status of this? Didn't you close this the other day?

**Comment by nunoh** [comment] 2016-01-08 17:11
bump @Oscar-Rodrigues

**Comment by nunoh** [comment] 2016-02-27 17:55
Closing as this seem to not be applying anymore.

**Comment by Oscar-Rodrigues** [comment] 2016-03-19 17:42
Reopening this as it's becoming noticeable again on iPad when the number of total particles is above ca. 10.

**Comment by Oscar-Rodrigues** [comment] 2016-04-21 16:42
So this is the status as of today:

the slowness is definitely being caused by ofSoundPlayer(). Tested disabling code related to images, graphics and calculations with little to no impact on this issue. But when disabling sound triggering, everything runs smoothly. 

We opened a different project to test the sound response in iOS specifically ([here](https://github.com/Digitopia/iOSAudioTest)), and opened a topic in the openFrameworks forum [here](https://forum.openframeworks.cc/t/ios-ofsoundplayer-causing-frame-rate-to-drop/23242). 

Awaiting responses.

**Comment by Oscar-Rodrigues** [comment] 2016-05-05 15:02
So the parallel project I mentioned before is now running on a stable 60 fps, even when triggering multiple sounds per second. I used, however, an openFrameworks addon which is only available for iOS. Awaiting for next week's meeting before deciding to implement this change for Gamult-iOS, which would fix this problem.

**Comment by nunoh** [comment] 2016-05-22 17:51
I would close this, but still not sure if it is truly solved. While in the iPhone simulator (version 5) it runs quite smoothly, even though being the simulator, when connected to a real iPad, with full particles, the FPS drops to a not so good ~30 fps and there is some noticeable lag. @Oscar-Rodrigues can you try running in your iPad and see if you get the same behaviour?

**Comment by Oscar-Rodrigues** [comment] 2016-06-02 15:29
This was fixed by commit 252dbf3ffcd5424d765ece39481100010a5d348f (merging branches to master)

**Closed as completed by Oscar-Rodrigues** 2016-06-02 15:29 UTC
Labels: bug, ios
