### ISSUE TITLE
Welcome Tiago

### ISSUE THREAD

**Issue by nunoh** [Digitopia/Gamult#101] opened 2016-04-28 23:02 UTC
Hey there @p1nh0  cc @Oscar-Rodrigues 
- [x] Follow [building instructions](https://github.com/Digitopia/Gamult/wiki/Building-Instructions)
- [x] Compile for OSX
- [x] Install [Zenhub](https://www.zenhub.io/) browser extension
- [x] [Close this issue with a commit message](https://help.github.com/articles/closing-issues-via-commit-messages/)

Then, take a look at our Zenhub board and grab any planned issue that is still not assigned to anyone. #85 seems like a good starting point provided is completely independent from the rest and relatively self-contained. Not the most interesting though.. 

welcome aboard 🚢

**Comment by p1nh0** [comment] 2016-04-29 16:13
how do make those check-boxes in issues ?

**Comment by p1nh0** [comment] 2016-04-29 16:59
with oF 0.9.3 couldn't compile, giving the following error: 
SwipeRecognition.h file not found

**Comment by nunoh** [comment] 2016-04-30 14:59
> how do make those check-boxes in issues ?

with `- [ ]` an empty checkbox and `- [x]` for checked one.

FYI, you can look (and edit) any comment by clicking the pencil icon, in order to see the corresponding markdown.
<img width="831" alt="screen shot 2016-04-30 at 15 58 08" src="https://cloud.githubusercontent.com/assets/1161423/14936752/6118bf98-0eec-11e6-887b-f9e4810f6ffe.png">

> with oF 0.9.3 couldn't compile, giving the following error: 
> SwipeRecognition.h file not found

This seems like @Oscar-Rodrigues can give a hand here. 

Have you compiled and run any of the examples (`openFrameworks/examples`) successfully though?

**Comment by Oscar-Rodrigues** [comment] 2016-05-05 15:25
@p1nh0 , that was strange. But should be fixed now, I basically removed all access to swipeRecognition.h when not working for iOS. Give it a try ;)

**Comment by p1nh0** [comment] 2016-05-06 16:02
Able to compile and run App...but...it gets super slow as I add particles. Is this normal or is this caused by debugging (printing to console and maybe other things I'm not aware of right now)?  

When "building for running" it compiles but makes no product. Is there a way to compile the app for running purposes ?

**Comment by p1nh0** [comment] 2016-05-06 16:38
ok...so I added a keyboard shortcut to disable the cout buffer...but it is still pretty slow...
see how to disable cout buffer here (it's the last answer):
http://stackoverflow.com/questions/30184998/how-to-disable-cout-output-in-the-runtime

**Comment by nunoh** [comment] 2016-05-06 21:24
Good thing you bring this up, since we could start to standardize how we handle debug messages in Digitopia C++ code at least. The "proper" programming way of doing this is not with direct `cout` like we've been doing all along. There is this concept of a logger, that openFrameworks provides with `ofLog()`, so that each message has a "logging level" i.e. notice, verbose, debug, etc, and then we can set which level we want to use at runtime, in the `setup()` method typically and hence we can turn console output on and off quite easily and with more control then now.

**Comment by Oscar-Rodrigues** [comment] 2016-05-07 11:42
Just FYI, mine is running ultra-fast.

@p1nho can you actually get a grasp on the frameRate as you add particles?
Something like:

cout << ofGetFrameRate() << endl;

Nuno Hespanhol notifications@github.com escreveu no dia sexta, 6/05/2016
às 22:24:

**Comment by p1nh0** [comment] 2016-05-07 15:19
@Oscar-Rodrigues without any particles the frame rate is approx. 60fps
after adding some particles the frame rate drops to 12fps

**Comment by p1nh0** [comment] 2016-05-07 15:51
@nunoh I'm opening an issue to implement ofLog() and making a fork and PR to solve it

**Closed as completed** 2016-05-08 20:20 UTC
Labels: chore
